services:
  - type: web
    name: irys-faucet-batch
    env: python
    buildCommand: |
      pip install -r requirements.txt
      playwright install chromium
    startCommand: |
      playwright install chromium
      gunicorn app:app
    envVars:
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: /opt/render/.cache/ms-playwright
    plan: free
    autoDeploy: true
    branch: main
