services:
  - type: web
    name: irys-faucet-batch
    env: python
    buildCommand: |
      pip install -r requirements.txt
      playwright install chromium
    startCommand: python app.py
    # 其他配置参数可选...
